updating publish steps to use flub

diff --git a/tools/pipelines/templates/include-publish-npm-package-steps.yml b/tools/pipelines/templates/include-publish-npm-package-steps.yml
--- a/tools/pipelines/templates/include-publish-npm-package-steps.yml
+++ b/tools/pipelines/templates/include-publish-npm-package-steps.yml
@@ -10,6 +10,9 @@ parameters:
 - name: feedName
   type: string
 
+- name: feedKind
+  type: string
+
 - name: official
   type: string
 
@@ -71,43 +74,33 @@ steps:
     targetType: 'inline'
     workingDirectory: $(Pipeline.Workspace)/pack/${{ parameters.artifactPath }}
     script: |
-      tag="--tag canary"
+      set -eu -o pipefail
+
+      echo "Artifact path: ${{ parameters.artifactPath }}"
+      tag="--tag rc"
       if [[ "$(release)" == "release" ]]; then
         if [ "$(isLatest)" = "true" ]; then
           tag="--tag latest"
         fi
       elif [[ "$(Build.SourceBranch)" = refs/heads/main ]]; then
-        tag="--tag next"
+        tag="--tag dev"
       fi
       echo Tag: $tag
+
       cp .npmrc ~/.npmrc
-      t1=0
-      for f in *.tgz
-      do
-          npm publish $f $tag ${{ parameters.publishFlags }} 2>&1 | tee publish_log
-          if grep -q "npm ERR!" "publish_log"
-          then
-              if ! grep -q "You cannot publish over the previously published versions" "publish_log"
-              then
-                let t1+=1
-              else
-                echo Package has already been published.
-                local_f="${f}_local"
-                mv "$f" "$local_f"
-                package_name=$(grep -oP 'npm notice package: \K.*' "publish_log")
-                npm pack $package_name
-                if cmp -s "$f" "$local_f"
-                then
-                  echo Continuing as published package matches the current one that was attempting to be released.
-                else
-                  echo ERROR: Published package does not match the current one attempting to be released for the same version.
-                  let t1+=1
-                fi
-                rm "$f"
-                mv "$local_f" "$f"
-              fi
-          fi
-          rm publish_log
-      done
+
+      maximumRetryIfNetworkError=3
+      tarballsDir=$(Pipeline.Workspace)/pack/${{ parameters.artifactPath }}
+      orderFile=$(Pipeline.Workspace)/pack/packagePublishOrder-${{ parameters.feedKind }}.txt
+
+      # execute the publish command
+      flub publish tarballs \
+      --dir $tarballsDir \
+      --orderFile $orderFile \
+      --publishArgs "$tag" \
+      --retry $maximumRetryIfNetworkError \
+      --verbose
+
+      # Clean up; remove the npmrc
       rm ~/.npmrc
-      exit $t1
+      exit 0
